namespace master_project.Utils
{
    public class AppEnums
    {
        public enum Metric
        {
            NPM = 1,
            NCM = 2,
            NAM = 3,
            NUM = 4,
            NOM = 5,
            NMM = 6,
            NASM = 7,
            NAGM = 8,
            NIM = 9,
            NATC1 = 10,
            NATC2 = 11,
            NOPC1 = 12,
            NOPC2 = 13,
            NASC=14,
            CBC=15,
            DIT=16,
            NSUPC=17,
            NSUBC=18,
            DAC=19,
            SIZE2=20,
            MHF=21,
            AHF=22,
            MIF=23,
            AIF=23

        }
        public enum Type
        {
            Package = 1,
            Class = 2,
            Interface = 3,
            Association = 4,
            Dependency = 5,
            Generalization = 6,
            Realization = 7,
            InnerClass = 8,
            InnerInterface = 9,
            Object = 10,
            AssociationObject = 11,
            DependencyPackage = 12,
            AssociationPackage = 13,
            DependencyObject = 14,
            PackageImport = 15,
            PackageMerge = 16,
            Usage = 17,
            Actor = 18,
            UseCase = 19,
            Interaction = 20,
            LifeLine = 21,
            Message = 22,
            CombinedFragment = 23,
            InteractionOperand = 24,
            Component = 25,
            Transtion = 26,
            CompositeState = 27,
            SimpleState = 28,
            PseudoState = 29,
            FinalState = 30,
            Port = 31,
            Provided = 32,
            Required = 33,
            Property = 34,
            Connector = 35,
            InformationFlow = 36,
            CollaborationUse = 37,
            ActionState = 38,
            Action = 39,
            DecisionNode = 40,
            ActivityFinalNode = 41,
            InitialNode = 42,
            ControlFlow = 43,
            ActivityPartition = 44,
            ForkNode = 45,
            FlowFinalNode = 46,
            ObjectFlow = 47,
            OutputPin = 48,
            InputPin = 49,
            Activity = 50,
            DataStoreNode = 51,
            CentralBufferNode = 52,
            ExceptionHandler = 53,
            ExceptionInput = 54,
            InterruptibleActivityRegion = 55,
            AcceptEventAction = 56,
            InterruptingEdge = 57,
            ActivityParameterNode = 58


        }

    }
}